[package]
name = "fltk-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.13"
fltk-flex = "0.2.1"
fltk-theme = "0.7.1"

